config/routes.rb
Rails.application.routes.draw do
  resources :searches
  devise_for :users
  resources :jobs

  root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
end

app/models/search.rb
class Search < ActiveRecord::Base

	def search_jobs
	  jobs = Job.all
	  jobs = jobs.where(["title LIKE ?","%#{keywords}%"]) if keywords.present?
	  jobs = jobs.where(["description LIKE ?","%#{languages}%"]) if languages.present?
	  jobs = jobs.where(["salary LIKE ?","%#{salary}%"]) if salary.present?
	  jobs = jobs.where(["company LIKE ?","%#{company}%"]) if company.present?
	  return jobs
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.where(["description LIKE ?","%#{params[:search]}%"])
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :description, :company, :salary, :link)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:keywords, :languages, :salary, :company)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Available Jobs</h1>

<div class="col-md-6 col-md-offset-3 table-responsive">
  <table class="table">
    <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><strong>Title:</strong></td>
        <td><%= job.title %></td>
      </tr>
      <tr>
        <td><strong>Company:</strong></td>
        <td><% if job.company.present? %><%= job.company %> <% end %></td>
      </tr>      
      <tr>
        <td><strong>Description:</strong></td>
        <td><%= job.description %></td>
      </tr>
      <tr>
        <td><strong>Salary:</strong></td>
        <td><%= number_to_currency(job.salary) %></td>
      </tr>
      <tr>
        <td><strong>Link:</strong></td>
        <td><%= job.link %></td>
      </tr>
      <tr>
        <% if user_signed_in? %>
          <td>
          <%= link_to 'Show', job %>
          <% if job.user == current_user %>
            <%= link_to 'Edit', edit_job_path(job) %>
            <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= link_to 'Post a Job', new_job_path %>
</div>

<br>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>
<p>
  <strong>Company:</strong>
  <% if @job.company.present? %>
  	<%= @job.company %>
  <% end %>
</p>
<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>

<p>
  <strong>Link:</strong>
  <%= @job.link %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Get Placed", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Advanced Search', new_search_path %></li>
        <li><%= form_tag jobs_path, :method => 'get' do %>
              <%= text_field_tag :search, params[:search] %>
              <%= submit_tag "Search" %>
            <% end %>
        </li>
        <% if user_signed_in? %>
          <li><%= link_to "Post a New Job", new_job_path, class: "active" %></li>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path,method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
          <li>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</na

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Getjob</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <p class="alert"><%= alert %></p>
  <div class="container">
<br />
    
  </div>	
	<%= yield %>
  </body>
</html>

app/views/searches/_form.html.erb
<%= form_for @search, html: {class: "pure-form"} do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :languages %><br>
    <%= f.text_field :languages %>
  </div>
  <div class="field">
    <%= f.label :salary %><br>
    <%= f.number_field :salary %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>
<div class="container">
<%= render 'form' %>
<%= link_to 'Back', searches_path %>
</div>

app/views/searches/show.html.erb
<div class="col-md-6 col-md-offset-3 table-responsive">
  <table class="table table-striped table-hover">
    <tbody>
    <% @search.search_jobs.each do |job| %>
      <tr>
        <td><strong>Title:</strong></td>
        <td><%= job.title %></td>
      </tr>
      <tr>
        <td><strong>Company:</strong></td>
        <td><% if job.company.present? %><%= job.company %> <% end %></td>
      </tr>      
      <tr>
        <td><strong>Description:</strong></td>
        <td><%= job.description %></td>
      </tr>
      <tr>
        <td><strong>Salary:</strong></td>
        <td><%= number_to_currency(job.salary) %></td>
      </tr>
      <tr>
        <td><strong>Link:</strong></td>
        <td><%= job.link %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', new_search_path %>